name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    name: Build Push Dockerimage
    runs-on: ubuntu-latest

    steps:
    -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: dyannary
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
        cd material-react-app
        docker build . --tag dyannary/pad-lab3:${{ github.sha }}
        docker tag dyannary/pad-lab3:${{ github.sha }} dyannary/pad-lab3:latest
        docker push dyannary/pad-lab3:${{ github.sha }}
        docker push dyannary/pad-lab3:latest

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to server
    steps:
    - name: SSH command executions
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cat ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username dyannary --password-stdin
          docker pull dyannary/pad-lab3:latest
          docker-compose up -d
    
    
  
